### ISSUE TITLE
Ground truth optical flow

### ISSUE THREAD

**Issue by katsunoriohnishi** [gulvarol/surreal#1]
Hi,
thank you for sharing such a great dataset. I think this dataset is very useful for Computer Vision community. :grinning:

>First large-scale person dataset to generate depth, body parts, optical flow, 2D/3D pose, surface normals ground truth for RGB video input. 
http://www.di.ens.fr/willow/research/surreal/data/

I can only find raw video, depth, segmentation, and meta-info in the downloaded dataset.
Would you also release ground truth optical flow, please?

**Comment by gulvarol** [comment]
Hi, thanks for your interest! I will update the release by adding the ground truth optical flow in the next version, currently you can generate your own data for that.

**Comment by katsunoriohnishi** [comment]
Thank you for quick response!
I'm looking forward to next update.
