### ISSUE TITLE
Is MoSH code available?

### ISSUE THREAD

**Issue by akshaykgupta** [gulvarol/surreal#14]
Hi,

I am trying to create my own dataset using skeleton recordings from Kinect cameras. I wished to know if the MoSH code to map joint positions to SMPL model is available publicly? I contacted the original authors but they did not respond. Any help would be appreciated.

**Comment by gulvarol** [comment]
MoSh code is not available to the best of my knowledge. I suggest to have a look at SMPLify code for fitting SMPL model to joints data http://smplify.is.tue.mpg.de/

**Comment by akshaykgupta** [comment]
Thanks, I'll check it out
