### ISSUE TITLE
Correspondence between texture map and SMPL model

### ISSUE THREAD

**Issue by xingyizhou** [gulvarol/surreal#15]
Hi Gul, 
  Thanks for sharing the great project! I am curious about how the texture UV mapping works on the rendering. If I understood correctly about the graphics pipline, you will need a uv coordinate associated with each of the 6890 SMPL vertices. Where is the uv data from? It seems that the uv data is created here https://github.com/gulvarol/surreal/blob/master/datageneration/main_part1.py#L172 ? Are they provided in the SMPL .fbx model? Looking forward to your reply. Thanks!

**Comment by gulvarol** [comment]
Yes, they are provided in the SMPL .fbx model. If you load the model in Blender, it would be in Armature > f_avg > Untitled. You can visualize the UV map if you click on the UV Editor.

**Comment by xingyizhou** [comment]
Thanks Gul!
