### ISSUE TITLE
Joint annotation of "Head Top"

### ISSUE THREAD

**Issue by MaxChu719** [gulvarol/surreal#18]
The two most common real human dataset LSP and MPII, they both have "head top" in their joint annotations. Can you also add this to your output?

**Comment by gulvarol** [comment]
Thanks for the comment. SMPL body model (http://smpl.is.tue.mpg.de/) does not have a "head top" as a joint. You can sample a point from the mesh vertices if you want something similar to MPII etc.

**Comment by MaxChu719** [comment]
Thanks for the reply. Is the mesh vertices can be deduced form your pre-compiled training set? As it would be better to used your pre-compiled training set as other researcher then can use the same training set for better comparison. Sorry that i didn't take a closer look at your code yet, i need to adjust my research schedule if i need to alter the code and re-generate my own training data.

**Comment by gulvarol** [comment]
Yes, the existing dataset provides the pose and shape parameters of the SMPL model that allow to recover the mesh.
