### ISSUE TITLE
h36m seg/depth gt

### ISSUE THREAD

**Issue by strawberryfg** [gulvarol/surreal#19]
Hey there,

I might have missed this, but I was wondering if the repo contains ground truth segmentation/depth of H36M dataset or anything related to training on Synth+H36M / H36M only?

Thanks!

**Comment by gulvarol** [comment]
Unfortunately, we are not able to release the ground truth segmentation/depth data on H36M dataset due to license issues. Sorry for any inconvenience.

**Comment by strawberryfg** [comment]
@gulvarol  Thanks for the instant reply!
