### ISSUE TITLE
2D pose inverted

### ISSUE THREAD

**Issue by Rasec8401** [gulvarol/surreal#2]
Hi, thanks for posting this interesting and useful dataset. I am testing the data generation and when i plot the joints on the frames of the video they seem to be rotated 180 degrees. How can i fix it ?

Thanks for your response.

**Comment by Rasec8401** [comment]
Temporarily i added these to the function get_bone_locs:

#####Rotating bone2D locations
    bone_locations_2d_new[:,0] = ((bone_locations_2d[:,0] - bone_locations_2d[0,0])*(-1) + bone_locations_2d[0,0])
    bone_locations_2d_new[:,1] = ((bone_locations_2d[:,1] - bone_locations_2d[0,1])*(-1) + bone_locations_2d[0,1])

    return(bone_locations_2d_new, bone_locations_3d)

**Comment by gulvarol** [comment]
Thanks for pointing that out, I will fix it. I subtract the y coordinates of the 2D pose from 240 (height), I forgot to put that in the code.

In Matlab, I did this:
`joints2D(2, :, :) = 240 - joints2D(2, :, :);`

The data should have the correct version.
