### ISSUE TITLE
about joints2D and joints3D

### ISSUE THREAD

**Issue by gimikk** [gulvarol/surreal#20]
Hi!
I have a question about the joints parameter reading from _info.mat file
Because I read a joints3d from mat file, But it's location is weird.
For example, the first coordinate is [-0.3, -0.9, 1.1].
joints2D is okay.
What do I do?

**Comment by gulvarol** [comment]
Can you clarify what you mean by weird location, please? joints3D denote 3D joint positions in meters.

**Comment by koelscha** [comment]
What is the reference point? [-0.3, -0.9, 1.1] meters from?
