### ISSUE TITLE
surreal `idx_info.pickle` mismatch the smpl_data file `smpl_data.npz`

### ISSUE THREAD

**Issue by chingswy** [gulvarol/surreal#22]
In the file `idx_info.pickle`, there are some info starts with `h36m`, however, the `smpl_data.npz` provided doesn't contain the pose of h36m, so if we directly use the code to generate images, it will raise some errors. To avoid this, I removed h36m items in `idx_info.pickle`, but I wonder if the pose data of h36m is available? Thanks.

**Comment by gulvarol** [comment]
Yes, please remove h36m items to avoid these errors. This data was removed from smpl_data.npz due to license issues.
