### ISSUE TITLE
how to get the cloth from the surreal dataset?

### ISSUE THREAD

**Issue by Designbook1** [gulvarol/surreal#23]
Dear sir,
        when I download the marval dataset, I can not find the cloth image, would you please tell me how to get the cloth image? Thank you so much!
![image](https://user-images.githubusercontent.com/9363289/50324313-3bf8e780-0519-11e9-88b8-66178a89446e.png)

**Comment by Designbook1** [comment]
#     cloth        [1xT cell]      - names of texture image files
From the info.mat, I just get this:
        array([u'nongrey_male_0164.jpg'], dtype='<U21'),
        array([u'nongrey_male_0164.jpg'], dtype='<U21'),
        array([u'nongrey_male_0164.jpg'], dtype='<U21'),
        array([u'nongrey_male_0164.jpg'], dtype='<U21'),
        array([u'nongrey_male_0164.jpg'], dtype='<U21'),
        array([u'nongrey_male_0164.jpg'], dtype='<U21')

but, where can I find the 'nongrey_male_0164.jpg' image?

**Comment by gulvarol** [comment]
Just to clarify, the dataset name is not marvel, it is surreal.
The clothing images are in `smpl_data/textures/` as explained in the README: https://github.com/gulvarol/surreal#211-smpl-data
