### ISSUE TITLE
Number of body parts

### ISSUE THREAD

**Issue by koelscha** [gulvarol/surreal#24]
In the segmentation model, there are 14 body parts + 1 background. In the dataset, there are 24 body parts + 1 background. How do they relate? I couldn't find a mapping.

**Comment by gulvarol** [comment]
Yes, it's here:
{2, 12, 9, 2, 13, 10, 2, 14, 11, 2, 14, 11, 2, 2, 2, 1, 6, 3, 7, 4, 8, 5, 8, 5}
https://github.com/gulvarol/surreal/blob/master/training/loader_SURREAL.lua#L85
