### ISSUE TITLE
How generate own synthetic data

### ISSUE THREAD

**Issue by GianMassimiani** [gulvarol/surreal#33]
I am trying to generate my own synthetic data, using different background images, different camera focal length and mean distance. I followed the instructions on the README, however I don’t fully understand how to generate a large set of video clips. By running `run.sh` only one clip is generated. How can I generate many clips as in your dataset? Thanks

**Comment by gulvarol** [comment]
It depends on your platform. I provided some scripts [here](https://github.com/gulvarol/surreal/tree/master/datageneration/misc) to give an idea for the jobs I launched. I parallelized them on a CPU cluster. The specifics of each cluster is different, so you would need to figure that out.

**Comment by GianMassimiani** [comment]
Thanks for the reply. Basically, if I understand correctly, I could just read line by line the `job_list.txt` file, then setting set the `JOB_PARAMS` variable in`run.sh` to that line, and run the script to generate a new video clip?

**Comment by gulvarol** [comment]
Yes, you can do that.
