### ISSUE TITLE
Questions about Human Textures

### ISSUE THREAD

**Issue by nbei** [gulvarol/surreal#34]
Hi, Thanks a lot for your work.

I feel confused about your human texture set. In the original paper, you say that there exist two set of human textures. How can we get the source information of the human textures, which indicates which set they come from.

**Comment by gulvarol** [comment]
If the texture image starts with `grey_*` it comes from CAESAR, the ones with `nongrey_*` come from clothed set. You will notice the difference by looking at the texture images.
