### ISSUE TITLE
Segmentation Creation or Visualization is Broken

### ISSUE THREAD

**Issue by zazizou** [gulvarol/surreal#37]
![01_01_c0001_segm](https://user-images.githubusercontent.com/17546468/61071945-9785b680-a412-11e9-8e66-56e28a861228.png)

Hi,

This image represents the segmentation I got from generating the synthetic data. I've followed sctrictly the procedure explained for data creation except , I needed to use blender 2.9 in order to install *pip* (ssl certificate issue otherwise).

There is an empty part in the visualized upper body in this image. Similar results are obtained when downloading directly the data instead of creating them.

Any help that can explained this observation ?

Thanks in advance

**Comment by gulvarol** [comment]
Do you use the matlab scripts in the demo folder for creating this visualization? It seems you are passing 15 as the number of part segments argument? There should be 24 parts + 1 background in the original segmentation after rendering. I group some of them into 15 for training a CNN. Maybe try visualizing with simple imagesc function.

**Comment by zazizou** [comment]
Thank you  for replying, I appreciate your help.

You guessed right, I have used the  demo folder scripts you have provided for my visualization ;-). I am  actually discovering .mat files, MATLAB programming and Blender so please bear with me... I will try imagesc function and will send you back the result.

My final purpose is also for training a CNN. In the end, I will need to combine the 24 parts into only 3 main parts : head, upper body and lower body.  Could you give me any guidance or recommendation?

Best regards

**Comment by zazizou** [comment]
![out_imagesc](https://user-images.githubusercontent.com/17546468/61204844-a27c6780-a6ee-11e9-840c-90211d4346d1.jpg)
 
This is the new result using *imagesc* funtion from MATLAB and using the colormap from demo folder. So the segmentation was correctly done, thanks for the hint ! 

As for my training project, what will be the most efficient way of merging the segmentation parts since I only need 3 main parts instead of the 24 ?  Is there a way of generating data  with only the segmentation parts I need or should I combine the parts at visualization level ?

Thanks in advance

**Comment by gulvarol** [comment]
Please check the training code where I merge the 24 parts into 15. You would need to pass your own indices.

Here is where I define the indices to merge:
https://github.com/gulvarol/surreal/blob/8af8ae195e6b4bb39a0fb64524a15a434ea620f6/training/loader_SURREAL.lua#L85

And here is the function that does the merging:
https://github.com/gulvarol/surreal/blob/8af8ae195e6b4bb39a0fb64524a15a434ea620f6/training/donkey.lua#L43-L48

**Comment by zazizou** [comment]
Some results : 
![segm_merged_imagesc](https://user-images.githubusercontent.com/17546468/61307152-1baeb400-a7ee-11e9-9646-682405e7c017.png)
![segm_merged_showmat](https://user-images.githubusercontent.com/17546468/61307153-1baeb400-a7ee-11e9-8236-cd798c29ebd0.png)

**Comment by zazizou** [comment]
Trying to understand the merging process  for the segmentation parts, I  repeated your work for the  main 15 parts. I think I should now be able to redo the process for head, upper body and lower body parts. 

The pictures of the previous post represent from up to down a visualisation using *imagesc* and your *showMatfile.m* script respectively of the merged segmentation. But as you can noticed, from the picture obtained via *showMatfile.m*, the head part  does not appear. I still do not know what I am missing...

Thank you again for your great assistance !! I think we can close this issue
