### ISSUE TITLE
Using Surreal for Human Action Recognition

### ISSUE THREAD

**Issue by rayush7** [gulvarol/surreal#38]
Hi @gulvarol 

Thank you for a great dataset.

Actually I want to use Surreal dataset for human action recognition task. In this regard, I have following two questions.

1. From where do I obtain the information about specific action type in the videos? Do you store that information in any of the mat files?

2. Also if I want to generate videos for custom actions according to my own requirement then how can I achieve that?

Thank you

**Comment by gulvarol** [comment]
1. I do not store any information about actions, but the naming is consistent with the original CMU MoCap dataset. You could use the categories from http://mocap.cs.cmu.edu/ or the annotations from this paper: https://arxiv.org/pdf/1603.07772.pdf

2. You would need to replace the pose parameters loaded from smpl_data.npz with your own motion sequences.

Good luck!

**Comment by rayush7** [comment]
Alright thanks. Regarding the second question if I have understood correctly then :

Firstly I need to have 3D MoCap marker data for my custom actions then fit SMPL body model on this 3D MoCap marker data using MoSh. And finally store the parameters of the SMPL body model in smpl_data.npz

Is this what you suggested?

**Comment by gulvarol** [comment]
The way you obtain the SMPL body parameters is up to you. It depends what data is available. MoSh is one option when you have marker data, but note that the code is not publicly available. I would say this is a research question on its own. But yes, you should fit SMPL parameters to your custom actions and store in smpl_data.npz for minimal code change.

**Comment by rayush7** [comment]
Thank you for clarifying my doubt. I will also try to contact MoSh authors regarding this.

**Comment by sunshineatnoon** [comment]
Hi @gulvarol Thanks for open-sourcing this great work. I would also like to use the action labels and I'm not familiar with the CMU Mocap dataset, could you please point me to exactly where I can find the them? Is it in the name of the video clip or the info.mat files. Thanks!

**Comment by gulvarol** [comment]
CMU Mocap is not meant for action recognition, but I pointed to a few places above where you can obtain such information. Yes, the name of the CMU MoCap sequence when you download their data, and the name of Surreal sequences are consistent. This name redundantly appears everywhere in Surreal, you can read it in readme: `<sequenceName>/ #e.g. 01_01`.

With the followup Surreact work, we are obtaining smpl sequences for actions by monocular motion estimation: https://www.di.ens.fr/willow/research/surreact/

**Comment by sunshineatnoon** [comment]
> CMU Mocap is not meant for action recognition, but I pointed to a few places above where you can obtain such information. Yes, the name of the CMU MoCap sequence when you download their data, and the name of Surreal sequences are consistent. This name redundantly appears everywhere in Surreal, you can read it in readme: `<sequenceName>/ #e.g. 01_01`.
> 
> With the followup Surreact work, we are obtaining smpl sequences for actions by monocular motion estimation: https://www.di.ens.fr/willow/research/surreact/

Thanks so much!
