### ISSUE TITLE
could you please zip small files into a big tar.gz file?

### ISSUE THREAD

**Issue by etworker** [gulvarol/surreal#4]
I'm afraid it is not efficient to download a lot of small files instead of big tar.gz file, could you please help to zip them? many thanks if it is possible!

**Comment by gulvarol** [comment]
I agree, sorry for the inconvenience. That was to allow partial download. You can use [this link](https://lsh.paris.inria.fr/SURREAL_v1.tar.gz) to download the whole dataset, I also added it to the Readme.
