### ISSUE TITLE
Scipy in Blener 2.78

### ISSUE THREAD

**Issue by usrFabian** [gulvarol/surreal#40]
Hi Gül,
thank you for sharing your great work.
I'm generating my own data using your scripts. Therefore I've installed Blender 2.78a as you recommend in the readme. Unfortunately, the python version coming with Blender 2.78a uses an outdated version of OpenSSL which made it impossible to install scipy using pip for me.
I've just used [Blender 2.79b](https://download.blender.org/release/Blender2.79/blender-2.79b-linux-glibc219-x86_64.tar.bz2). That works great for me and it should work for everyone since the python APIs of these versions are compatible.
I just wanted to document that somewhere for people running into the same problems. Maybe you can change the readme.

Best
Fabian

**Comment by gulvarol** [comment]
Hi Fabian, thanks for the note. Yes I am aware that pip does not work anymore with Blender 2.78a. Unfortunately, that was the Blender version that worked on the cluster I used, the newer ones complained about glibc errors. The solution is to either use newer Blender versions or to install dependencies such as scipy in a separate environment and to add that environment to `PYTHONPATH`. I will add a note to readme.
