### ISSUE TITLE
How to get the SMPL shape parameters?

### ISSUE THREAD

**Issue by xdcheese** [gulvarol/surreal#42]
Hi @gulvarol ,

Thanks for releasing the code.

I would like to create my own synthetic data with different shapes. I find that in [#2-create-your-own-synthetic-data](https://github.com/gulvarol/surreal#2-create-your-own-synthetic-data) there are:

 maleshapes       [1700 x 10] - SMPL shape parameters for 1700 male scans
 femaleshapes     [2103 x 10] - SMPL shape parameters for 2103 female scans 

Those parameters are not provided in smpl_data.npz. I'm wondering where can I get those parameters?

Thanks!

**Comment by gulvarol** [comment]
Hi, I have just checked the `smpl_data.npz` file. I cannot reproduce the problem. Shape parameters can be extracted from that file by:
``` python
import numpy as np
smpl_data = np.load('smpl_data.npz')
smpl_data['maleshapes']  # 1700 x 10
smpl_data['femaleshapes']  # 2103 x 10
```

**Comment by xdcheese** [comment]
Thank you very much!
