### ISSUE TITLE
The pretrained model finetuned on Human 3.6M dataset

### ISSUE THREAD

**Issue by amrbenattia** [gulvarol/surreal#43]
Thanks for your great work
you have provided 4 pretrained models (2 for segmentation and 2 for depth estimation), I am wondering if you can provide the model that is fine-tuned on Human3.6M training dataset?
Regards,
Amr

**Comment by gulvarol** [comment]
Unfortunately, we are not able to release the models trained on our H36M ground truth due to license issues. Sorry for any inconvenience.

**Comment by amrbenattia** [comment]
Thanks so much for your kind reply
