### ISSUE TITLE
Use smplx instead of smpl

### ISSUE THREAD

**Issue by MohammedHossam** [gulvarol/surreal#44]
Thanks for your great work.
I understand that you are using smpl model (embedded) and I wonder if I can use smplx instead of smpl in the synthetic data creation part? and how?

Thanks

**Comment by gulvarol** [comment]
Yes, this repository is using the initial SMPL model. You would have to adapt the code yourself to support the recent "expressive" SMPL-X model, e.g. provide additional pose parameters for the hands and faces. The current model only poses the 23 body joints.
