### ISSUE TITLE
Cannot access dataset website

### ISSUE THREAD

**Issue by asd40708** [gulvarol/surreal#46]
Hi,

I'm interesting in your great work and want to try something with the dataset, but the link in README.md seems broken.
![Screenshot from 2020-06-17 14-47-51](https://user-images.githubusercontent.com/41198647/84864672-94c32500-b0a9-11ea-8fc4-89f2f67798c8.png)

Would you fix this problem? Or it's just something I miss so I can't access the website?

**Comment by gulvarol** [comment]
Hi, sorry there is a temporary problem on the server. Should be back soon.

**Comment by asd40708** [comment]
The link works well now, thanks.
