### ISSUE TITLE
Reproducing the depth estimation results on the synthetic test set

### ISSUE THREAD

**Issue by Dominoer** [gulvarol/surreal#51]
Hi, I am reproducing the depth estimation results on the synthetic test set. But the results I got are quite different from the results reported in the paper. As the paper suggested 'To interpret the error in real world coordinates, we multiply it by the quantization constant (45mm).' I can only get 4.39 * 45mm = 197.8mm (RMSE). That number is far bigger than the number reported in the paper. It would be very appreciated if you could run your released model on the depth estimation baseline too.

_Originally posted by @Dominoer in https://github.com/gulvarol/surreal/issues/9#issuecomment-718753229_

**Comment by gulvarol** [comment]
Hi, I think there is something wrong with these numbers. The released model `model_depth_mp4.t7` should not be too different than 72.9mm RMSE. Maybe a few mm difference due to different frame decoding quality, but not more.

**Comment by Dominoer** [comment]
Thanks for your quick reply! I redownloaded the surreal dataset to see if the performances match. It is very strange that the segmentation performances are exactly the same as you said in [the last issue](https://github.com/gulvarol/surreal/issues/9#issuecomment-718753229), whereas the depth estimation doesn't match at all. It would be very appreciated if you could run a quick test. I tested the performances on both tar file and source file (download script).

**Comment by YunseokJANG** [comment]
Hi, @Dominoer . I suffer the exact same issue: mismatch in "depth", so I wonder whether you've resolved this issue or not. If you did, then could you share how you've adjusted this issue (what I am missing)?
