### ISSUE TITLE
How to align depth and RGB of H3.6M

### ISSUE THREAD

**Issue by funihang** [gulvarol/surreal#55]
Hi,

Thanks for your excellent work. I read your paper and found you use H3.6M to do the depth estimation in the experimental section. But I am confused about how to align depth and RGB images of H3.6M. If you can provide the method or code, I would appreciate it.

Thanks.

**Comment by gulvarol** [comment]
As noted in issue https://github.com/gulvarol/surreal/issues/19, we cannot provide H3.6M-related data/code. This is due to the request by the Human3.6M dataset owners. Sorry for the inconvenience.
