### ISSUE TITLE
Output path is wrongly set in main_part2.py

### ISSUE THREAD

**Issue by HaiyongJiang** [gulvarol/surreal#6]
Dear author, 
      It's nice of you to create such a tool for data generation. When I run the code, I happened to find some bugs. In main_part2.py, the output path is wrongly setup (`"output_path = join(output_path, 'run%d' % runpass, name.replace(" ", ""))"`). It should use the name from idx_info rather than body_data.

**Comment by gulvarol** [comment]
Could you describe more your problem please? I couldn't understand the issue. Where does the line (https://github.com/gulvarol/surreal/blob/master/datageneration/main_part2.py#L115) use the name from 'body_data'? And what exactly is 'body_data' here?
