### ISSUE TITLE
How to generate dataset with camera view from top?

### ISSUE THREAD

**Issue by mnauf** [gulvarol/surreal#62]
I want to generate the same dataset with different camera elevations (height). Where do I need to make changes?

**Comment by gulvarol** [comment]
Please have a look at my other repository which is cleaner:

https://github.com/gulvarol/surreact/blob/73a1851b01dffb79d5b1d7afa08a6bfe91646954/datageneration/utils/blenderutils.py#L7

Setting `--cam_height` is sufficient:
https://github.com/gulvarol/surreact/blob/73a1851b01dffb79d5b1d7afa08a6bfe91646954/datageneration/utils/argutils.py#L24

You can check this issue as well:

https://github.com/gulvarol/surreact/issues/1
